// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apimodels.Context;

#nullable disable

namespace apimodels.Migrations
{
    [DbContext(typeof(MaqueteContext))]
    [Migration("20220912181540_CampoData")]
    partial class CampoData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("apimodels.models.Maquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ArquivoMaquete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DataPublicacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DescricaoMaquete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ImgMaquete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MaqueteAtiva")
                        .HasColumnType("bit");

                    b.Property<string>("NomeMaquete")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Maquetes");
                });
#pragma warning restore 612, 618
        }
    }
}
